import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  weight: ["500", "600", "700", "800", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "block",
});

export const metadata = {
  title: "User Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
